name: Feature request
description: Request a new feature
labels: [ "feature request" ]
assignees:
  - 1fexd
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Describe the feature you would like to see in LinkSheet in as much detail as possible. Also include why this feature is needed, who it benefits and (if applicable) what possible alternatives would be
    validations:
      required: true