name: Build nightly APK

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      #      - name: Setup Android modded android.jar
      #        uses: 1fexd/setup-modded-android-jar@0.0.3
      #        env:
      #          ANDROID_SDK_VERSION: 33

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-        

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "keystore.jks"
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew assembleFossNightly
        env:
          GITHUB_WORKFLOW_RUN_ID: ${{ github.run_id }}
          KEYSTORE_FILE_PATH: ${{ steps.android_keystore.outputs.filePath }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: linksheet-nightly
          path: app/build/outputs/apk/foss/nightly/*.apk

      - name: Get info
        id: get_info
        shell: bash
        run: |
          echo "FILE_NAME=$(basename app/build/outputs/apk/foss/nightly/*.apk .apk)" >> "$GITHUB_OUTPUT"
          echo "LATEST_STABLE_RELEASE=$(gh release list | grep 'Latest' | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"

      - name: Release note
        id: release_note
        run: |
          RELEASE_NOTE="* View the difference to the last nightly release: [$LAST_COMMITS_SHA...$GITHUB_SHA](https://github.com/$GITHUB_REPOSITORY/compare/$LAST_COMMITS_SHA...$GITHUB_SHA)\n
                        * View the difference to the last stable release [$LATEST_STABLE_RELEASE...$GITHUB_SHA](https://github.com/$GITHUB_REPOSITORY/compare/$LATEST_STABLE_RELEASE...$GITHUB_SHA)" 
          
          echo RELEASE_NOTE >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV<
        env:
          LAST_COMMITS_SHA: ${{ github.event.before }}
          LATEST_STABLE_RELEASE: ${{ steps.get_info.outputs.LATEST_STABLE_RELEASE }}

      - run: gh release create -R $NIGHTLY_REPO $NIGHTLY_TAG app/build/outputs/apk/foss/nightly/*.apk --latest --notes $RELEASE_NOTE
        env:
          GITHUB_TOKEN: ${{ secrets.NIGHTLY_REPO_ACCESS_TOKEN }}
          NIGHTLY_REPO: ${{ vars.NIGHTLY_REPO_URL }}
          NIGHTLY_TAG: ${{ steps.get_info.outputs.FILE_NAME }}
          RELEASE_NOTE: ${{ env.ONE_LINE_TEXT_ENV_VAR }}
