name: Build nightly APK

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install JQ
        run:  sudo apt-get install jq -y

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      #      - name: Setup Android modded android.jar
      #        uses: 1fexd/setup-modded-android-jar@0.0.3
      #        env:
      #          ANDROID_SDK_VERSION: 33

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-        

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "keystore.jks"
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew assembleFossNightly
        env:
          GITHUB_WORKFLOW_RUN_ID: ${{ github.run_id }}
          KEYSTORE_FILE_PATH: ${{ steps.android_keystore.outputs.filePath }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: linksheet-nightly
          path: app/build/outputs/apk/foss/nightly/*.apk

      - name: Get file name
        id: get_file_name
        shell: bash
        run: cat "FILE_NAME=$(basename app/build/outputs/apk/foss/nightly/*.json .json)" | jq '.elements[0].versionCode' >> "$GITHUB_OUTPUT"

      - name: Nightly release notes
        id: release_note
        uses: 1fexd/gh-create-release-notes@0.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          stable-repo: ${{ github.repository }}
          nightly-repo: ${{ vars.NIGHTLY_REPO_URL }}
          last-commit-sha: ${{ github.event.before }}
          commit-sha: ${{ github.sha }}

      - run: gh release create -R "$NIGHTLY_REPO" $NIGHTLY_TAG app/build/outputs/apk/foss/nightly/*.apk --latest --notes "$RELEASE_NOTE"
        env:
          GITHUB_TOKEN: ${{ secrets.NIGHTLY_REPO_ACCESS_TOKEN }}
          NIGHTLY_REPO: ${{ vars.NIGHTLY_REPO_URL }}
          NIGHTLY_TAG: ${{ steps.get_file_name.outputs.FILE_NAME }}
          RELEASE_NOTE: ${{ steps.release_note.outputs.releaseNote }}

      - name: Trigger a remote workflow
        uses: 1fexd/gh-trigger-remote-action@0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.NIGHTLY_PRO_REPO_ACESS_TOKEN }}
          OWNER: 1fexd
          REPO: LinkSheetPro
          EVENT_TYPE: rebuild-nightly
